version: '3'

services:
    db:
        container_name: toodool-database
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: toodooldb
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"